node {

   stage('SCM check out') {
      git 'https://github.com/infinitude-public/opendata.git'
   
   }
   
   stage('Compile package') {
     // get maven home path
     def mvnHome = tool name: 'maven-3', type: 'maven'
     sh "${mvnHome}/bin/mvn -f jboot/pom.xml clean package"
   }
   
   
   stage('Email notification') {
      mail bcc: '', body: '''Hi,
      Welcome to jenkins email alerts
      Thanks You''', cc: '', from: '', replyTo: '', subject: 'Jenkins job', to: 'sirishmax@gmail.com'
   
   }


}