server:
  port: ${PORT:8085}
  servlet:
   context-path: /jboot
  
  
  
#Setting the logging levels for the service
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG